name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: check-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/test.yml') }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Check Lint, Format and Type Hint
        run: poetry run task check

  test-ros1:
    strategy:
      fail-fast: false

      matrix:
        ros:
          - { distro: noetic, os: ubuntu-20.04 }

    runs-on: ${{ matrix.ros.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros.distro }}

      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: test-ros1-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/test.yml') }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Unit Test
        run: |
          source /opt/ros/${{ matrix.ros.distro }}/setup.bash
          roscore &
          poetry run task test

  test-ros2:
    strategy:
      fail-fast: false

      matrix:
        ros:
          - { distro: humble, os: ubuntu-22.04 }
          - { distro: iron, os: ubuntu-22.04 }
          - { distro: rolling, os: ubuntu-22.04 }

    runs-on: ${{ matrix.ros.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros.distro }}

      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: test-ros2-${{ matrix.ros.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/test.yml') }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Unit Test
        run: |
          source /opt/ros/${{ matrix.ros.distro }}/setup.bash
          poetry run task check
