name: Test

on:
  push:
    branches: "*"

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache Packages
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: check-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/test.yml') }}

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Check Lint, Format and Type Hint
        run: poetry run task check

  test-ros1:
    strategy:
      fail-fast: false

      matrix:
        ros:
          - { distro: melodic, os: ubuntu-18.04 }
          - { distro: noetic, os: ubuntu-20.04 }

    runs-on: ${{ matrix.ros.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache Packages
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: test-ros1-${{ matrix.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/test.yml') }}

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install -E ros1 --no-interaction

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.distro }}

      - name: Unit Test
        run: |
          roscore &
          poetry run task test

  test-ros2:
    strategy:
      fail-fast: false

      matrix:
        ros:
          - { distro: foxy, os: ubuntu-20.04 }
          - { distro: galactic, os: ubuntu-20.04 }
          - { distro: humble, os: ubuntu-22.04 }
          - { distro: rolling, os: ubuntu-20.04 }

    runs-on: ${{ matrix.ros.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache Packages
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: test-ros2-${{ matrix.ros.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/test.yml') }}

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install -E ros2 --no-interaction

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.ros.distro }}

      - name: Unit Test
        run: poetry run task check
